<?php
	return [
		'channel_id' => '渠道', 
		'channel_account_id' => '渠道账号', 
		'order_id' => '订单号', 
		'warehouse_id' => '仓库', 
		'logistics_id' => '物流方式', 
		'shipper_id' => '发货人', 
		'type' => '类型', 
		'cost' => '运费', 
		'weight' => '系统重量', 
		'actual_weight' => '实际重量', 
		'tracking_no' => '追踪号', 
		'tracking_link' => '追踪链接', 
		'is_remark' => '是否备注', 
		'is_upload' => '是否上传', 
		'email' => 'email', 
		'shipping_name' => '发货人姓名', 
		'shipping_address1' => '发货人地址1', 
		'shipping_address2' => '发货人地址2', 
		'shipping_city' => '发货城市', 
		'shipping_state' => '发货省市(自治州)', 
		'shipping_zipcode' => '发货邮编', 
		'shipping_phone' => '发货电话', 
		'remark' => '备注', 
		'printed_at' => '打印时间', 
		'delieved_at' => '妥投时间', 
		'status' => '状态'
	];